### ISSUE TITLE
Unsure how to supervise a pool with 0.17

### ISSUE THREAD

**Issue by nickelser** [celluloid/celluloid-supervision#19]
With 0.16, I had a class like:

```ruby
class Overseer < Celluloid::SupervisionGroup
   supervise Baz, as: :baz
   pool Foobar, as: :foobars
end
  
Overseer.run!
```

That seems to map to (almost)

```ruby
overseer = Celluloid::Supervision::Configuration.define([
  {type: Baz, as: :baz},
  {type: Foobar, as: :foobars, size: Celluloid.cores} # ???
])

overseer.deploy
```

but that doesn't seem to supervise a pool. (`E, [2015-07-05T15:06:16.368813 #11187] ERROR -- : Actor crashed!
NoMethodError: undefined method `size' for #<Foobar:...>`

Do I need to make a pool-wrapper class? Is this documented somewhere that I'm missing? I see the line in the relevant code seems to be commented out (https://github.com/celluloid/celluloid-supervision/blob/7fad80b371b0d861c3fab4d442c20dd355cdcb43/lib/celluloid/supervision/constants.rb#L34), but I can't really trace the logic of how plugins are loaded.

I know that 0.17 was just released yesterday, but I am eager early adopter as the `Terminating task` info messages were really dragging me down :)

**Comment by nickelser** [comment]
As a side note, some of the `Terminating task` messages are still warnings :(

```
W, [2015-07-05T15:21:13.379927 #11346]  WARN -- : Terminating task: type=:finalizer, meta={:dangerous_suspend=>true, :method_name=>:__shutdown__}, status=:receiving
	Celluloid::Task::Fibered backtrace unavailable. Please try `Celluloid.task_class = Celluloid::Task::Threaded` if you need backtraces here.
D, [2015-07-05T15:21:13.380781 #11346] DEBUG -- : Terminating task: type=:call, meta={:dangerous_suspend=>false, :method_name=>:start}, status=:sleeping
	Celluloid::Task::Fibered backtrace unavailable. Please try `Celluloid.task_class = Celluloid::Task::Threaded` if you need backtraces here.
```

Just noting that I did try to do

```ruby
overseer = Celluloid::Supervision::Configuration.define([
  {type: Baz, as: :baz}
])

Celluloid::Actor[:foobars] = Foobar.pool

overseer.deploy
```

But that does not seem to have the same error-handing behavior as before:

```
E, [2015-07-05T15:22:12.010392 #11360] ERROR -- : Actor crashed!
Interrupt: Interrupt
	(irb):1:in `block (2 levels) in irb_binding'
	<snip>:in `call'
	<snip>:in `dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `public_send'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:76:in `block in task'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:363:in `block in task'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/task.rb:57:in `block in initialize'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/task/fibered.rb:14:in `block in create'
   (0.4ms)  COMMIT
D, [2015-07-05T15:22:12.010700 #11360] DEBUG -- : Celluloid::Supervision::Container::Pool: async call `dispatch` aborted!
Interrupt: Interrupt
	(irb):1:in `block (2 levels) in irb_binding'
	<snip>:in `call'
	<snip>:in `dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `public_send'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:76:in `block in task'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:363:in `block in task'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/task.rb:57:in `block in initialize'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/task/fibered.rb:14:in `block in create'
	(celluloid):0:in `remote procedure call'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/call/sync.rb:45:in `value'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/proxy/sync.rb:40:in `method_missing'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/proxy/cell.rb:20:in `_send_'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-pool-0.20.0/lib/celluloid/supervision/container/pool.rb:45:in `_send_'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-pool-0.20.0/lib/celluloid/supervision/container/pool.rb:199:in `method_missing'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `public_send'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:76:in `block in task'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:363:in `block in task'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/task.rb:57:in `block in initialize'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/task/fibered.rb:14:in `block in create'
   (0.9ms)  SELECT CURRENT_TIMESTAMP
E, [2015-07-05T15:22:12.010812 #11360] ERROR -- : thread crashed
Interrupt: Interrupt
	(irb):1:in `block (2 levels) in irb_binding'
	<snip>:in `call'
	<snip>:in `dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `public_send'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/call/sync.rb:16:in `dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:76:in `block in task'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:363:in `block in task'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/task.rb:57:in `block in initialize'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/task/fibered.rb:14:in `block in create'
	(celluloid):0:in `remote procedure call'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/call/sync.rb:45:in `value'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/proxy/sync.rb:40:in `method_missing'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/proxy/cell.rb:20:in `_send_'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-pool-0.20.0/lib/celluloid/supervision/container/pool.rb:45:in `_send_'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-pool-0.20.0/lib/celluloid/supervision/container/pool.rb:199:in `method_missing'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `public_send'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/calls.rb:28:in `dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/call/async.rb:7:in `dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:50:in `block in dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/cell.rb:76:in `block in task'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/actor.rb:363:in `block in task'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/task.rb:57:in `block in initialize'
	/usr/local/lib/ruby/gems/2.2.0/gems/celluloid-0.17.0/lib/celluloid/task/fibered.rb:14:in `block in create'
E, [2015-07-05T15:22:12.011786 #11360] ERROR -- : Actor crashed!
Celluloid::DeadActorError: attempted to call a dead actor
```

Was trying to chase down the new behavior stuff, and also noticed that the pool size is misspelled here: https://github.com/celluloid/celluloid-pool/blob/master/lib/celluloid/supervision/container/behavior/pool.rb#L63 (probably totally unrelated).

Anywho, Celluloid is awesome, sorry to spam you with reports after you just released it!

**Comment by nickelser** [comment]
I think I finally figured out the "right" way to do things from the spec here: https://github.com/celluloid/celluloid-pool/blob/3598c2a06ea1beb00e4f4222d09eaad24cb5929c/spec/celluloid/pool/container_spec.rb

```ruby
Class.new(Celluloid::Supervision::Container) do
  supervise type: Baz, as: :baz
  pool Foobar, as: :foobars
end.run!
```

But it still has the dead actor problem (where before in 0.16 it would restart the actor), here we still get

```
E, [2015-07-05T15:32:03.349516 #11496] ERROR -- : thread crashed
Interrupt: Interrupt
```

and then

```
E, [2015-07-05T15:32:03.350380 #11496] ERROR -- : Actor crashed!
Celluloid::DeadActorError: attempted to call a dead actor
```

**Comment by digitalextremist** [comment]
@nickelser thanks for the detailed notes. The version in the spec is a bit overly formal, but does work, the first way you showed was with a `Configuration` which is also a bit more than you need perhaps. Good news is, both `celluloid-supervision` and `celluloid-pool` were taken out of `celluloid` itself, as you know, so any fixes that might be required can happen here, and happen faster. I will look at this and get back to you.
