### ISSUE TITLE
Fast restarting Actors cause Supervisors to die.

### ISSUE THREAD

**Issue by clonezone** [celluloid/celluloid-supervision#28]
Running the program `supervise-suicidal-actor`:

```ruby
#!/usr/bin/env ruby

require 'celluloid/current'

class SuicidalActor
    include Celluloid

    def initialize
        async.die

        return
    end

    def die
        raise 'Die.'

        return
    end
end

puts 'Start.'

SuicidalActor.supervise as: :racer

sleep 9999
```

will result in output like

```
Start.
E, [2016-02-18T16:58:57.764000 #13897] ERROR -- : Actor crashed!
RuntimeError: Die.
    ./supervise-suicidal-actor:15:in `die'
    org/jruby/RubyKernel.java:1823:in `public_send'
    <install/path>/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
    <install/path>/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
    <install/path>/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
    <install/path>/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
    <install/path>/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
    <install/path>/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
    <install/path>/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
…
[the above will repeat for a while for hopefully obvious reasons]
…
E, [2016-02-18T16:58:58.589000 #13897] ERROR -- : Error ( RuntimeError ) at start of supervised instance of SuicidalActor
E, [2016-02-18T16:58:58.590000 #13897] ERROR -- : Actor crashed!
RuntimeError: a container instance went missing. This shouldn't be!
    <install/path>/celluloid-supervision-0.20.5/lib/celluloid/supervision/container.rb:118:in `restart_actor'
    <install/path>/celluloid-0.17.3/lib/celluloid/cell.rb:15:in `block in call'
    <install/path>/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
    <install/path>/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
    <install/path>/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
    <install/path>/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

Supervisors shouldn't disappear just because their Actors go nuts.

**Comment by ylansegal** [comment]
I've seen some of this same behavior myself, where depending on the crash, the supervisor itself dies. Very interested in this issue.

**Comment by tarcieri** [comment]
It sounds like the supervision system is racy
